FROM ubuntu:latest

RUN apt update && \
	DEBIAN_FRONTEND=noninteractive TZ=Europe/London \
	apt install -y pandoc make texlive texlive-latex-extra texlive-fonts-extra gpg curl npm python3-pip
RUN pip install matplotlib
RUN curl https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | gpg --dearmor > conda.gpg \
	&& install -o root -g root -m 644 conda.gpg /usr/share/keyrings/conda-archive-keyring.gpg \
	&& gpg --keyring /usr/share/keyrings/conda-archive-keyring.gpg --no-default-keyring --fingerprint 34161F5BF5EB1D4BFBBB8F0A8AEB4F8B29D82806 \
	&& echo "deb [arch=amd64 signed-by=/usr/share/keyrings/conda-archive-keyring.gpg] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" > /etc/apt/sources.list.d/conda.list \
	&& apt update && DEBIAN_FRONTEND=noninteractive TZ=Europe/London apt install -y conda
RUN export PATH=/opt/conda/bin:$PATH \
	&& conda install -y -c conda-forge pandoc-plot
RUN npm install --global mermaid-filter

ENV PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


WORKDIR /context
