[defaults]
username = "alvie"
password = "passoword"
try-multiple = false
run-local = true
output = "out"

[[remotes]]
name = "local"
host = "http://localhost:5000"
default = true
job-id = "dc1f1627-7fb9-4bca-989c-535eb79bc899"

[remotes.ssh]
host = "alvie@localhost"
